version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: b9-mongo-container
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: hituadmin
            MONGO_INITDB_ROOT_PASSWORD: jdhfkjfiouerqw
            MONGO_INITDB_DATABASE: b9db
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro